import React, {
  useRef, useEffect, useState, useCallback, Suspense,
} from "react";
import { Canvas, useFrame, useThree } from "@react-three/fiber";
import { OrbitControls, Line, Html, Float } from "@react-three/drei";
import * as THREE from "three";
import gsap from "gsap";
import { animate } from "animejs";
import { motion, AnimatePresence } from "framer-motion";

// ─────────────────────────────────────────
// API base
// ─────────────────────────────────────────
const API_BASE = import.meta.env.VITE_API_URL || "http://localhost:8000";

// ─────────────────────────────────────────
// GLOBAL STYLES
// ─────────────────────────────────────────
const GlobalStyles = () => (
  <style>{`
    @import url('https://fonts.googleapis.com/css2?family=Rajdhani:wght@300;400;500;600;700&family=Noto+Sans+JP:wght@100;300;400;700;900&family=Outfit:wght@900&display=swap');

    *, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }
    body {
      overflow: hidden;
      background: #ffffff;
      font-family: 'Rajdhani', sans-serif;
      cursor: crosshair;
      color: #000;
      user-select: none;
    }
    ::-webkit-scrollbar { width: 3px; }
    ::-webkit-scrollbar-track { background: #f5f5f5; }
    ::-webkit-scrollbar-thumb { background: #000; }

    @keyframes blink {
      0%, 49% { opacity: 1; }
      50%, 100% { opacity: 0; }
    }

    .anime-bg {
      position: fixed; top: 0; left: 0; width: 100%; height: 100%;
      pointer-events: none; z-index: 10; opacity: 0.15;
    }
    .scanline {
      position: absolute; width: 100%; height: 2px;
      background: rgba(0,0,0,0.08); top: 0;
    }
    .grid-overlay {
      position: absolute; width: 200%; height: 200%;
      background-image: 
        linear-gradient(to right, rgba(0,0,0,0.05) 1px, transparent 1px),
        linear-gradient(to bottom, rgba(0,0,0,0.05) 1px, transparent 1px);
      background-size: 50px 50px;
      transform: translate(-25%, -25%);
    }

    /* Target specific class generated by Drei's Html component if needed */
    .node-label-html {
      pointer-events: none !important;
      z-index: 1 !important;
    }
  `}</style>
);

// ─────────────────────────────────────────
// ANIME.JS BACKGROUND
// ─────────────────────────────────────────
function AnimeBackground() {
  const containerRef = useRef();
  const scanlineRef = useRef();

  useEffect(() => {
    animate('.grid-overlay', {
      translateX: ['-25%', '-30%'],
      translateY: ['-25%', '-30%'],
      duration: 20000,
      loop: true,
      ease: 'linear'
    });

    animate('.scanline', {
      translateY: ['0vh', '100vh'],
      duration: 3000,
      loop: true,
      ease: 'linear'
    });
  }, []);

  return (
    <div className="anime-bg" ref={containerRef}>
      <div className="grid-overlay" />
      <div className="scanline" ref={scanlineRef} />
    </div>
  );
}

// ─────────────────────────────────────────
// UI COMPONENTS
// ─────────────────────────────────────────

function CornerBrackets({ color = "rgba(0,0,0,0.15)", size = 20, inset = 24 }) {
  const corners = [
    { top: inset, left: inset, borderTop: `1.5px solid ${color}`, borderLeft: `1.5px solid ${color}` },
    { top: inset, right: inset, borderTop: `1.5px solid ${color}`, borderRight: `1.5px solid ${color}` },
    { bottom: inset, left: inset, borderBottom: `1.5px solid ${color}`, borderLeft: `1.5px solid ${color}` },
    { bottom: inset, right: inset, borderBottom: `1.5px solid ${color}`, borderRight: `1.5px solid ${color}` },
  ];
  return (
    <>
      {corners.map((s, i) => (
        <div key={i} style={{ position: "fixed", width: size, height: size, zIndex: 100, pointerEvents: "none", ...s }} />
      ))}
    </>
  );
}

function TopHeader() {
  return (
    <div style={{
      position: "fixed", top: 0, left: 0, right: 0, height: 60,
      display: "flex", justifyContent: "space-between", alignItems: "flex-end",
      padding: "0 24px 10px", borderBottom: `1px solid rgba(0,0,0,0.08)`, zIndex: 100,
    }}>
      <div style={{ fontSize: "10px", letterSpacing: "5px", color: "#000", fontFamily: "monospace", opacity: 0.6, fontWeight: 700 }}>
        35.6764 N, 139.6500 E // UTM: 54S
      </div>
      <div style={{ fontSize: "10px", letterSpacing: "5px", color: "#000", fontFamily: "monospace", fontWeight: 900 }}>
        NOTION_BRAIN // CORE_SYSTEM_V3.0
      </div>
    </div>
  );
}

function HeroGrid({ onSubmit }) {
  return (
    <div style={{ flex: 1, display: "flex", flexDirection: "column", borderBottom: `1px solid rgba(0,0,0,0.08)` }}>
      <div style={{ display: "grid", gridTemplateColumns: "1.4fr 1fr 0.8fr", height: "100%" }}>
        <div style={{ padding: "40px", borderRight: `1px solid rgba(0,0,0,0.08)` }}>
          <h2 style={{ fontSize: "32px", lineHeight: "1.1", maxWidth: "450px", fontWeight: 500, letterSpacing: "-0.01em" }}>
            The Notion MCP Challenge. Centralizing workflow with AI-powered docs, projects, and notes.
          </h2>
        </div>
        <div style={{ padding: "40px", borderRight: `1px solid rgba(0,0,0,0.08)`, fontSize: "11px", letterSpacing: "1.5px", lineHeight: "1.8" }}>
          <div style={{ color: "#999", marginBottom: "8px", fontWeight: 700 }}>SYSTEM_ORACLE:</div>
          <div>POWERED BY <span style={{ textDecoration: "underline" }}>NOTION MCP ENGINE</span> //</div>
          <div>SUMMARIZING NODES <span style={{ textDecoration: "underline" }}>STRUCTURALLY</span></div>
        </div>
        <div style={{ padding: "40px", fontSize: "11px", letterSpacing: "2px" }}>
          <div style={{ color: "#999", marginBottom: "8px" }}>2026 // EST</div>
          <button onClick={() => onSubmit("DEMO")} style={{ background: "none", border: "none", borderBottom: "1.5px solid #000", cursor: "pointer", fontSize: "11px", letterSpacing: "2px", fontWeight: 700 }}>INITIALIZE_DEMO_INSTANCE_</button>
        </div>
      </div>
      <div style={{ height: "140px", borderTop: `1px solid rgba(0,0,0,0.08)`, display: "flex" }}>
        {Array.from({ length: 14 }).map((_, i) => (
          <div key={i} style={{ flex: 1, borderRight: i === 13 ? "none" : `1.5px solid rgba(0,0,0,0.08)`, position: "relative", display: "flex", alignItems: "center", justifyContent: "center" }}>
             <div style={{ position: "absolute", top: -5, left: -1, width: 2, height: 10, background: "#000" }} />
             <div style={{ position: "absolute", top: -1, left: -5, width: 10, height: 2, background: "#000" }} />
             <div style={{ width: 10, height: 10, border: "0.5px solid rgba(0,0,0,0.1)", opacity: 0.5 }} />
          </div>
        ))}
      </div>
    </div>
  );
}

function MainTitle() {
  return (
    <div style={{ padding: "0 24px", position: "relative", overflow: "hidden", marginBottom: "40px" }}>
      <div style={{ display: "flex", alignItems: "baseline" }}>
         <h1 style={{ fontFamily: "'Outfit', sans-serif", fontSize: "clamp(80px, 14vw, 180px)", fontWeight: 900, letterSpacing: "-0.04em", lineHeight: "0.75", textTransform: "uppercase" }}>NOTION</h1>
         <h1 style={{ fontFamily: "'Outfit', sans-serif", fontSize: "clamp(80px, 14vw, 180px)", fontWeight: 300, letterSpacing: "-0.04em", lineHeight: "0.75", textTransform: "uppercase", WebkitTextStroke: "2.5px #000", color: "transparent", marginLeft: "0.08em" }}>BRAIN</h1>
      </div>
      <div style={{ position: "absolute", bottom: 0, right: 24, fontSize: "11px", letterSpacing: "4px", fontWeight: 700, border: "2px solid #000", padding: "6px 14px", background: "#000", color: "#fff" }}>
        SYSTEM_ID: MCP_2026
      </div>
    </div>
  );
}

function ConnectionPanel({ onSubmit }) {
  const [token, setToken] = useState("");
  const [focused, setFocused] = useState(false);
  return (
    <div style={{ padding: "50px 24px", display: "flex", gap: "80px", alignItems: "flex-end" }}>
       <div style={{ flex: 1 }}>
         <div style={{ fontSize: "10px", letterSpacing: "3px", color: "#999", marginBottom: "15px", fontWeight: 700 }}>&gt;_CONNECT WORKSPACE</div>
         <div style={{ border: `2px solid ${focused ? "#000" : "rgba(0,0,0,0.15)"}`, padding: "8px 20px", display: "flex", alignItems: "center", maxWidth: "450px", transition: "border-color 0.3s" }}>
           <span style={{ marginRight: "12px", fontWeight: 600, opacity: 0.3 }}>&gt;</span>
           <input value={token} onChange={e => setToken(e.target.value)} onFocus={() => setFocused(true)} onBlur={() => setFocused(false)} placeholder="secret_xxxxxx..." type="password" style={{ flex: 1, background: "none", border: "none", outline: "none", fontSize: "15px", fontFamily: "monospace", letterSpacing: "2px", fontWeight: 500 }} />
         </div>
       </div>
       <button onClick={() => onSubmit(token)} style={{ padding: "20px 50px", background: "#000", color: "#fff", border: "none", fontSize: "13px", letterSpacing: "4px", fontWeight: 700, cursor: "pointer", transition: "transform 0.2s" }} onMouseEnter={e => e.target.style.transform = "scale(1.02)"} onMouseLeave={e => e.target.style.transform = "scale(1)"}>EXECUTE_CONNECTION_</button>
    </div>
  );
}

// ─────────────────────────────────────────
// THREE.JS COMPONENTS
// ─────────────────────────────────────────
function StructuralBackground() {
  const count = 300;
  const positions = useRef(new Float32Array(count * 3));
  useEffect(() => {
    for (let i = 0; i < count; i++) {
      positions.current[i * 3 + 0] = (Math.random() - 0.5) * 120;
      positions.current[i * 3 + 1] = (Math.random() - 0.5) * 120;
      positions.current[i * 3 + 2] = (Math.random() - 0.5) * 120;
    }
  }, []);
  return (
    <group>
      {Array.from({ length: 25 }).map((_, i) => (
        <Float key={i} speed={3} rotationIntensity={1} floatIntensity={1}>
          <mesh position={[(Math.random() - 0.5) * 60, (Math.random() - 0.5) * 60, (Math.random() - 0.5) * 60]}>
            <boxGeometry args={[Math.random() * 8, 0.03, 0.03]} />
            <meshStandardMaterial color="#000" transparent opacity={0.04} />
          </mesh>
        </Float>
      ))}
      <points>
        <bufferGeometry>
          <bufferAttribute attach="attributes-position" count={count} array={positions.current} itemSize={3} />
        </bufferGeometry>
        <pointsMaterial size={0.15} color="#000" transparent opacity={0.1} />
      </points>
    </group>
  );
}

function NodeBlock({ node, isSelected, onNodeClick, assemblyDelay }) {
  const meshRef  = useRef();
  const groupRef = useRef();
  const [assembled, setAssembled] = useState(false);
  const [hovered,   setHovered]   = useState(false);

  useEffect(() => {
    if (!meshRef.current) return;
    meshRef.current.scale.setScalar(0.01);
    const tl = gsap.timeline({ delay: assemblyDelay });
    tl.to(meshRef.current.scale, { x: 1, y: 1, z: 1, duration: 0.8, ease: "slow(0.7, 0.7, false)" });
    tl.call(() => setAssembled(true));
    return () => tl.kill();
  }, [assemblyDelay]);

  useFrame(({ clock }) => {
    if (!groupRef.current || !assembled) return;
    const t = clock.elapsedTime;
    const seed = (node.id || "a").charCodeAt(0);
    groupRef.current.position.y = (node.position?.[1] || 0) + Math.sin(t * 1.2 + seed) * 0.3;
    if (isSelected) groupRef.current.rotation.y += 0.03;
  });

  return (
    <group position={node.position} onClick={(e) => { e.stopPropagation(); onNodeClick(node); }} onPointerEnter={() => { setHovered(true); document.body.style.cursor = "pointer"; }} onPointerLeave={() => { setHovered(false); document.body.style.cursor = "crosshair"; }}>
      <mesh ref={meshRef}>
        <boxGeometry args={[1.6, 1.6, 1.6]} />
        <meshStandardMaterial color={isSelected ? "#000" : (hovered ? "#333" : "#eee")} wireframe={!isSelected && !hovered} roughness={0} metalness={0.9} />
      </mesh>
      {isSelected && <Line points={[[0, -15, 0], [0, 15, 0]]} color="#000" lineWidth={0.8} transparent opacity={0.2} />}
      <Html center position={[0, 2.0, 0]} className="node-label-html" portal={document.body}>
        <div style={{ 
          background: isSelected ? "#000" : (hovered ? "rgba(0,0,0,0.85)" : "rgba(255,255,255,0.9)"), 
          color: (isSelected || hovered) ? "#fff" : "#000", 
          padding: "3px 12px", fontSize: "11px", fontWeight: 700, textTransform: "uppercase", letterSpacing: "2px", whiteSpace: "nowrap", border: isSelected ? "1.5px solid #000" : "1px solid rgba(0,0,0,0.15)", transition: "all 0.3s", backdropFilter: "blur(4px)",
          zIndex: isSelected ? 50 : 5, position: "relative"
        }}>
          {node.label}
        </div>
      </Html>
    </group>
  );
}

// ─────────────────────────────────────────
// MAIN APP
// ─────────────────────────────────────────

const CHALLENGE_TEXT = `We're excited to announce our newest challenge in partnership with Major League Hacking (MLH) and Notion! Running through March 29, the Notion MCP Challenge welcomes you to centralize your workflow with AI-powered docs, projects, and notes. 

JUDGING CRITERIA:
• Originality & Creativity
• Technical Complexity
• Practical Implementation

PRIZES: One winner will receive an invitation to chat with Ivan Zhao (CEO), $500 USD, and more. Submissions due March 29!`;

export default function App() {
  const [phase, setPhase] = useState("landing");
  const [data, setData] = useState({ nodes: [], links: [] });
  const [selectedNode, setSelectedNode] = useState(null);
  const [token, setToken] = useState("");
  const [nodeContent, setNodeContent] = useState("");
  const [loadingContent, setLoadingContent] = useState(false);
  const [error, setError] = useState("");

  const DEMO_DATA = {
    nodes: [
      { id: "1", label: "NOTION_MCP_CHALLENGE", position: [0, 0, 0], edited: new Date().toISOString() },
      { id: "2", label: "PRIZES_AND_BADGES", position: [15, 8, -5], edited: new Date().toISOString() },
      { id: "3", label: "JUDGING_CRITERIA", position: [-15, -8, 10], edited: new Date().toISOString() },
      { id: "4", label: "SUBMISSION_TEMPLATES", position: [8, -15, -12], edited: new Date().toISOString() },
      { id: "5", label: "HACKATHON_TEAM_HUB", position: [-10, 12, 15], edited: new Date().toISOString() },
    ],
    links: [
      { source: "1", target: "2" },
      { source: "1", target: "3" },
      { source: "1", target: "4" },
      { source: "1", target: "5" },
    ]
  };

  const handleSubmit = useCallback(async (customToken) => {
    if (customToken === "DEMO") {
      setPhase("loading");
      setTimeout(() => {
         setData(DEMO_DATA);
         setPhase("world");
      }, 1500);
      return;
    }
    setToken(customToken);
    setPhase("loading");
    setError("");
    try {
      const resp = await fetch(`${API_BASE}/api/graph`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ token: customToken }) });
      if (!resp.ok) throw new Error("CONNECT_ERROR");
      const resData = await resp.json();
      setData(resData);
      setPhase("world");
    } catch (err) {
      setError(err.message);
      setPhase("landing");
    }
  }, []);

  const fetchDetail = useCallback(async (node) => {
    setSelectedNode(node);
    if (node.id === "1") {
       setNodeContent(CHALLENGE_TEXT);
       return;
    }
    setLoadingContent(true);
    try {
      const resp = await fetch(`${API_BASE}/api/page/${node.id}?token=${token}`);
      const d = await resp.json();
      setNodeContent(d.content || "NODE_EMPTY.");
    } catch (err) {
      setNodeContent("SIGNAL_LOSS.");
    }
    setLoadingContent(false);
  }, [token]);

  return (
    <div style={{ width: "100vw", height: "100vh", background: "#ffffff", color: "#000" }}>
      <GlobalStyles />
      <AnimeBackground />
      <CornerBrackets />
      
      {phase === "landing" && (
        <div style={{ height: "100vh", display: "flex", flexDirection: "column", position: "relative", zIndex: 1 }}>
          <TopHeader />
          <div style={{ flex: 1, display: "flex", flexDirection: "column", padding: "60px 0 0" }}>
            <HeroGrid onSubmit={handleSubmit} />
            <div style={{ flex: 1 }} />
            <MainTitle />
            <ConnectionPanel onSubmit={handleSubmit} />
          </div>
        </div>
      )}

      {phase === "loading" && (
        <div style={{ height: "100vh", display: "flex", alignItems: "center", justifyContent: "center", flexDirection: "column", position: "relative", zIndex: 1 }}>
          <div style={{ fontSize: "13px", letterSpacing: "12px", fontWeight: 700, marginBottom: "25px", animation: "blink 1s infinite" }}>ESTABLISHING_SYNC_CONNECTION_</div>
          <div style={{ width: "250px", height: "2px", background: "rgba(0,0,0,0.08)", position: "relative" }}>
             <motion.div initial={{ width: 0 }} animate={{ width: "100%" }} transition={{ duration: 1.5 }} style={{ position: "absolute", top: 0, left: 0, height: "100%", background: "#000" }} />
          </div>
        </div>
      )}

      {phase === "world" && (
        <div style={{ width: "100%", height: "100%", position: "relative" }}>
          <div style={{ position: "fixed", top: 24, left: 24, zIndex: 100, display: "flex", alignItems: "center", gap: "25px" }}>
             <h2 style={{ fontSize: "16px", letterSpacing: "5px", fontWeight: 700, fontFamily: "Rajdhani" }}>NB_UNIVERSE_X1</h2>
             <button onClick={() => setPhase("landing")} style={{ background: "#000", color: "#fff", border: "none", padding: "6px 16px", fontSize: "10px", cursor: "pointer", fontWeight: 700, letterSpacing: "3px" }}>TERMINATE_SYNC</button>
          </div>
          
          <div id="canvas-container" style={{ width: "100%", height: "100%", position: "relative", zIndex: 50 }}>
            <Canvas camera={{ position: [0, 15, 50], fov: 40 }}>
              <ambientLight intensity={0.6} />
              <pointLight position={[30, 40, 30]} intensity={2.0} />
              <Suspense fallback={null}>
                <StructuralBackground />
                {data.nodes.map((node, i) => (
                  <NodeBlock key={node.id} node={node} isSelected={selectedNode?.id === node.id} onNodeClick={fetchDetail} assemblyDelay={i * 0.04} />
                ))}
                {data.links.map((link, i) => {
                  const s = data.nodes.find(n => n.id === (link.source.id || link.source));
                  const t = data.nodes.find(n => n.id === (link.target.id || link.target));
                  if (!s || !t) return null;
                  return <Line key={i} points={[s.position, t.position]} color="#000" lineWidth={0.8} transparent opacity={0.15} />;
                })}
              </Suspense>
              <OrbitControls autoRotate={!selectedNode} autoRotateSpeed={0.4} />
            </Canvas>
          </div>

          <AnimatePresence>
            {selectedNode && (
              <motion.div initial={{ x: "100%" }} animate={{ x: 0 }} exit={{ x: "100%" }} transition={{ type: "spring", damping: 28, stiffness: 220 }} style={{ 
                position: "fixed", right: 0, top: 0, bottom: 0, width: "500px", 
                background: "rgba(255,255,255,0.95)", backdropFilter: "blur(40px)", 
                borderLeft: "3.5px solid #000", zIndex: 9999, padding: "80px 50px", 
                display: "flex", flexDirection: "column", boxShadow: "-20px 0 40px rgba(0,0,0,0.1)" 
              }}>
                <div style={{ position: "absolute", top: 30, right: 30, display: "flex", gap: "25px" }}>
                   <a href={selectedNode.url} target="_blank" rel="noreferrer" style={{ fontSize: "11px", color: "#000", fontWeight: 700, letterSpacing: "2px", borderBottom: "2px solid #000", paddingBottom: "2px", textDecoration: "none" }}>OPEN_NOTION_SOURCE</a>
                   <button onClick={() => setSelectedNode(null)} style={{ border: "none", background: "none", cursor: "pointer", fontSize: "28px", padding: 0, fontWeight: 300 }}>×</button>
                </div>
                <div style={{ fontSize: "11px", color: "#777", letterSpacing: "4px", marginBottom: "15px", fontWeight: 700 }}>NODE_SYNC // INTELLIGENT_ORACLE</div>
                <h3 style={{ fontSize: "42px", fontWeight: 900, textTransform: "uppercase", marginBottom: "40px", lineHeight: 0.9, letterSpacing: "-0.02em", fontFamily: "Outfit" }}>{selectedNode.label}</h3>
                <div style={{ flex: 1, overflowY: "auto", borderTop: "2px solid #000", paddingTop: "40px" }}>
                   {loadingContent ? (
                     <div style={{ fontSize: "13px", letterSpacing: "6px", fontWeight: 700, animation: "blink 1s infinite" }}>GENERATING_CORE_SUMMARY...</div>
                   ) : (
                     <div style={{ lineHeight: 1.8, color: "#111", fontSize: "15px", fontWeight: 500, whiteSpace: "pre-wrap" }}>
                        {nodeContent}
                     </div>
                   )}
                </div>
                <div style={{ marginTop: "50px", fontSize: "10px", color: "#ccc", letterSpacing: "2px", borderTop: "1px solid #eee", paddingTop: "20px", display: "flex", justifyContent: "space-between" }}>
                   <span>RECORD_TAG: {selectedNode.id.slice(0, 8).toUpperCase()}</span>
                   <span>EDITS: {new Date(selectedNode.edited).toLocaleDateString()}</span>
                </div>
              </motion.div>
            )}
          </AnimatePresence>
          <div style={{ position: "fixed", bottom: 24, left: 24, zIndex: 100, fontSize: "10px", color: "#000", letterSpacing: "4px", fontWeight: 700 }}>SYNC_STATUS: ACTIVE // AI_SUMMARY_ENGINE: ENABLED</div>
        </div>
      )}
    </div>
  );
}